# Generated by Django 5.0.1 on 2024-02-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='User_Profile_images/'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trending_images/'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='trending_images/'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='trending_images/'),
        ),
    ]
