# Generated by Django 5.0.1 on 2024-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_featured_image_alter_featured_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='User_Profile_images/'),
        ),
    ]
